### ISSUE TITLE
Need better instruction in the README on how to run

### ISSUE THREAD

**Issue by damianof** [factsfinder/Zeus#3]
So I am running this, then browsing to http://localhost:8081 and i see only this:
React Native packager is running.
Visit documentation

Need better instruction in the README on how to run.

**Comment by factsfinder** [comment]
I've updated the readme a bit. Also right now I'm only developing for android, so don't bother about iOS for a while, unless you want to contribute for it you are more than welcome to do so.
When you visit localhost:8081, that is what you are supposed to see. Because as far as I know, React Native apps can only be tested on either mobiles on emulators. So install an Android SDK and all the required apps. If you are new to react native, then check some guides online. I'm closing this issue now.

**Comment by damianof** [comment]
Thank you. People might want to collaborate, but need more clear instructions.

**Comment by factsfinder** [comment]
No problem.
